#!/bin/bash
#PBS -l nodes=1:ppn=1,vmem=12g,walltime=00:30:00
#PBS -N app-network-matrices-2-mat
#PBS -V

# convert raw matrices to conmat datatype
time singularity exec -e docker://faskowit/app-fmri-2-mat ./make-datatype.py
